import { Inter } from "next/font/google"
import Image from "next/image"
import BgImg from "../../public/assets/bg/5570852.jpg";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={` bg-slate-900 ${inter.className}`}>
        <Image src={BgImg} loading='lazy' className='w-full grayscale-0 opacity-25 h-full object-cover fixed top-0 left-0 right-0 bottom-0' alt='bg' />
        {children}</body>
    </html>
  )
}
